# frozen_string_literal: true

source 'https://rubygems.org'

gem 'prometheus-client'
gem 'yabeda-http_requests',
    git: 'https://github.com/dsalahutdinov/yabeda-http_requests'
gem 'yabeda-prometheus'

gem 'puma'
gem 'rack'
gem 'sidekiq'

gem 'faraday', require: false
gem 'sniffer', '>= 0.4.0'
